feat: FormPhoneInput
Robbe95/wisemen-components pull request #1
Opened 2023-07-11 16:45 UTC by JeffreyNijs

2023-07-17 07:17 UTC, maltsavkiryl requested changes
paar kleine remarks. Misschien kunnen we nog extra leuke props toevoegen? Moeten ook eens zien of we "isRequired" enzo kunnen toevoegen aan FormInputField

2023-07-17 07:17 UTC, maltsavkiryl commented on src/components/form/phone-input/FormPhoneInput.vue
> +const input = computed({
type toevoegen

2023-07-17 07:17 UTC, maltsavkiryl commented on src/components/form/phone-input/FormPhoneInput.vue
> +  return `https://purecatamphetamine.github.io/country-flag-icons/3x2/${iso2}.svg`
is dit de meest reliable site voor die country svg?

2023-07-17 07:17 UTC, maltsavkiryl commented on src/components/form/phone-input/FormPhoneInput.vue
> +        ?
vraagteken?

2023-07-17 13:09 UTC, JeffreyNijs commented on src/components/form/phone-input/FormPhoneInput.vue
> +        ?
Vraagteken bij onbekende country. Gebeurt als bv het inputveld leeg is

2023-07-17 13:10 UTC, JeffreyNijs commented on src/components/form/phone-input/FormPhoneInput.vue
> +  return `https://purecatamphetamine.github.io/country-flag-icons/3x2/${iso2}.svg`
https://www.npmjs.com/package/country-flag-icons

2023-07-19 20:45 UTC, Robbe95 requested changes
Component moet ook nog toegevoegd worden aan het script
https://wisemen-components.netlify.app/story/docs-introduction-story-js
Hier staat die uitleg er voor

2023-07-19 20:45 UTC, Robbe95 commented on src/components/form/phone-input/FormPhoneInput.vue
> +  modelValue: string
Dit is niet meer nodig als ge defineModel gebruikt

2023-07-19 20:45 UTC, Robbe95 commented on src/components/form/phone-input/FormPhoneInput.vue
> +  (event: 'update:modelValue', value: string): void
Zelfde hier, is vervangen door defineModel

2023-07-19 20:45 UTC, Robbe95 commented on src/components/form/phone-input/FormPhoneInput.vue
> +const { isDisabled = false, defaultCountry = 'BE' as CountryCode } = defineProps<Props>()
as CountryCode is niet nodig, de string 'BE' is al van dat type

2023-07-19 20:45 UTC, Robbe95 commented on src/components/form/phone-input/FormPhoneInput.vue
> +      <p v-else class="w-6 text-center text-gray-400">
text-gray-400 is weg bij volgende release, er gaan enkel nog de kleuren zijn afgesproken met de designers, gebruikt text-muted-foreground

2023-07-19 20:45 UTC, Robbe95 commented on src/components/form/phone-input/FormPhoneInput.vue
> +  get: () => model.value,
Dit errored bij mij, omdat model.value undefined kan zijn, oftewel vangt ge hier undefined op door bv een lege string
`get: () => model.value ?? '',`
Oftewel maakt ge model required
`const model = defineModel<string>({ required: true})`
Model required maken lijkt me logischer

2024-01-18 08:35 UTC, closed without merging