Modal
Robbe95/wisemen-components pull request #3
Opened 2023-07-13 19:49 UTC by Robbe95

2023-07-17 07:19 UTC, maltsavkiryl commented on src/components/app/modal/AppModal.vue
>    hasNoCloseButton?: boolean
mss is `hideCloseButton` een gemakkelijkere naam? :P

2023-07-24 14:40 UTC, Tanya-Amber-L commented on src/components/app/modal/AppModal.story.vue
> +  hasHiddenCloseButton?: boolean
Why is this named "hidden" close button?

2023-08-15 09:23 UTC, maltsavkiryl commented on src/components/app/modal/AppModal.story.vue
> +  hasHiddenCloseButton?: boolean
maybe a better name would be "hideCloseButton"

2023-08-15 09:26 UTC, maltsavkiryl commented on src/components/app/modal/AppModal.vue
> +              <button v-if="!hasHiddenCloseButton" class="flex" @click="handleClickCloseButton">
wat doet die flex hier in dit geval?

2023-08-15 09:26 UTC, maltsavkiryl commented on src/components/app/modal/AppModal.vue
> +const hasHeader = computed<boolean>(() => !!(slots.icon || slots.title || title || icon))
ik zou persoonlijk computed altijd boven de functies zetten

2023-08-15 09:28 UTC, maltsavkiryl commented on src/components/app/modal/appModalVariants.ts
>    lg: 'w-[120ch]',
waarvoor/waarom ch?

2023-08-15 09:29 UTC, maltsavkiryl requested changes
Enkele vragen, zie comments :)

2024-01-18 08:35 UTC, closed without merging